logging:
  level:
    root: error
    com.czetsuyatech: debug

server:
  port: 8080

app:
  security:
    jwt:
      cognito:
        group-field: cognito:groups
        user-name-field: username
        pool-id: ${AWS_COGNITO_POOL_ID}
        region: ${AWS_COGNITO_REGION}